### ISSUE TITLE
Location button for deaf or no vc role people during the afk phase (not pre-afk)

### ISSUE THREAD

**Issue by Deaththth** [ewang2002/ToogaBooga#117]
This is a button to get the location, only accessible for certain roles which are configured namely:
- deaf
-  no-vc role (dungeoneer role)
This button would only be added to the afk phase, when everybody is getting dragged in. (Not pre-afk since it isnt meant to be early location.)

**Comment by ewang2002** [comment]
First option will be added as part of the priority role system.

What do you mean by the "no-vc role?" Do you mean like a button where someone can register to join a raid without being in vc?
