### ISSUE TITLE
"Missing Member Roles" for the missing permissions embed shows up twice

### ISSUE THREAD

**Issue by ewang2002** [ewang2002/ToogaBooga#144]
![image](https://user-images.githubusercontent.com/37031713/160296355-04ea3587-ee1f-4a1a-8a67-72e3f1a60fcb.png)

**Comment by dmansdman** [comment]
Is this still an issue? It looks fine in the code

**Comment by ewang2002** [comment]
Probably isn't. I'll close this and will reopen it if it comes back somehow
