### ISSUE TITLE
Improve the look of the O3 Console

### ISSUE THREAD

**Issue by dmansdman** [ewang2002/ToogaBooga#61]
Not sure if they all look like it, but the readability isn't great.  Also, why do all the names have [] next to them?

![image](https://user-images.githubusercontent.com/97406520/148849262-6e325a7b-e0d9-484d-96cb-1b37d415dcd4.png)

**Comment by ewang2002** [comment]
Is this something that still needs to be addressed?

**Comment by dmansdman** [comment]
Will remove empty brackets, might play around with it.
