### ISSUE TITLE
Caching staff members

### ISSUE THREAD

**Issue by ewang2002** [ewang2002/ToogaBooga#74]
When the bot starts up, we should fetch every member in every guild so that staff members are implicitly cached in the bot's caching system. From there, we should be able to track down who gets a staff role and who loses one via the role add/remove events.

**Comment by dmansdman** [comment]
Did you handle this in 1.1.0? I noticed that you implemented team-role logic.

**Comment by ewang2002** [comment]
Well I guess I indirectly handled this. I just had the bot listen to partial events, so that resolves that. Closing
