### ISSUE TITLE
Raid VC Name with Lock/Unlock emoji

### ISSUE THREAD

**Issue by ewang2002** [ewang2002/ToogaBooga#84]
Hard to tell between 🔓 and 🔒 in the channel names. Might be worth removing entirely.

**Comment by dmansdman** [comment]
Maybe we can use custom emojis, such as these (but better ofc)

![image](https://user-images.githubusercontent.com/97406520/150582174-825d1c40-7f95-4f8d-83fe-152b4796a7b8.png)

**Comment by ewang2002** [comment]
I don't think custom emojis display properly on Discord channels

**Comment by dmansdman** [comment]
Oh, in that case maybe just remove the lock emoji when it is unlocked, maybe replace it with some other emoji (like green checkmark or any emoji that signifies that it is ready to join)

**Comment by ewang2002** [comment]
That's fine w/ me

**Comment by dmansdman** [comment]
I'm 90% sure that discord SEVERLY rate limits updating vc names (like once per 10 mins or something), so this is an unrealistic item.  I think we will have to find a way to identify locked/unlocked through the raid embed instead
