### ISSUE TITLE
Toogabooga is getting the members completed and members failed backwards

### ISSUE THREAD

**Issue by Cemeteryyy** [ewang2002/ToogaBooga#94]
Title, Say 35 members complete and 3 fail, at the end of the run toogabooga says 35 members failed and 3 members completed

**Comment by dmansdman** [comment]
Please share who screenshot and other details.  This could be a result of the parsing API simply not detecting names well enough, rather than the logic being backwards.

**Comment by ewang2002** [comment]
I'm assuming this has been resolved and will close this accordingly.
